# Generated by Django 6.1 on 2026-08-18 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0012_alter_order_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notas de despacho'),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_company',
            field=models.CharField(blank=True, max_length=100, verbose_name='Empresa de transporte'),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Número de seguimiento'),
        ),
    ]
