# Generated by Django 6.1 on 2026-08-18 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0014_alter_order_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitud de entrega'),
        ),
        migrations.AddField(
            model_name='order',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitud de entrega'),
        ),
    ]
