# Generated by Django 6.1 on 2026-08-18 07:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0015_order_latitude_order_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='country',
            field=models.CharField(blank=True, default='Chile', max_length=100, verbose_name='País'),
        ),
        migrations.AddField(
            model_name='order',
            name='region',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Región / Estado'),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Comuna / Ciudad'),
        ),
    ]
