# Generated by Django 6.1 on 2026-08-19 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0016_order_country_order_region_alter_order_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_auth_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='Código de autorización'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_card_last4',
            field=models.CharField(blank=True, max_length=10, verbose_name='Últimos 4 dígitos'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_card_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='Tipo de tarjeta'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de confirmación de pago'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_installments',
            field=models.IntegerField(default=1, verbose_name='Número de cuotas'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('webpay', 'Webpay Plus (Transbank)'), ('mercadopago', 'Mercado Pago'), ('sandbox_card', 'Tarjeta de Crédito / Débito (Directa)'), ('transfer', 'Transferencia Bancaria Manual')], default='webpay', max_length=30, verbose_name='Método de pago'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_transaction_id',
            field=models.CharField(blank=True, max_length=150, verbose_name='ID de transacción'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente de Pago'), ('paid', 'Pagada / En Preparación'), ('shipped', 'Enviada / En Camino'), ('completed', 'Entregada / Completada'), ('cancelled', 'Cancelada')], default='pending', max_length=20),
        ),
    ]
