# Generated by Django 6.1 on 2026-08-19 04:41

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0017_order_payment_auth_code_order_payment_card_last4_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=150, verbose_name='Región destino')),
                ('weight_min_kg', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=6, verbose_name='Peso mínimo (kg)')),
                ('weight_max_kg', models.DecimalField(decimal_places=3, default=Decimal('5.000'), max_digits=6, verbose_name='Peso máximo (kg)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio del envío (CLP)')),
                ('courier_name', models.CharField(default='Starken', max_length=100, verbose_name='Courier')),
                ('estimated_days', models.CharField(default='3-5 días hábiles', max_length=50, verbose_name='Días estimados')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
            ],
            options={
                'verbose_name': 'Tarifa de Envío',
                'verbose_name_plural': 'Tarifas de Envío',
                'ordering': ['region', 'weight_min_kg'],
            },
        ),
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(default='Store Django', max_length=200, verbose_name='Nombre de la tienda')),
                ('store_email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email de la tienda')),
                ('store_phone', models.CharField(blank=True, default='', max_length=30, verbose_name='Teléfono de la tienda')),
                ('origin_commune', models.CharField(default='Pichidegua', max_length=100, verbose_name='Comuna de despacho')),
                ('origin_address', models.CharField(blank=True, default='', max_length=250, verbose_name='Dirección de bodega')),
                ('free_shipping_threshold', models.DecimalField(decimal_places=2, default=Decimal('59990.00'), max_digits=10, verbose_name='Monto mínimo para envío gratis (CLP)')),
                ('shipit_email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email cuenta Shipit')),
                ('shipit_token', models.CharField(blank=True, default='', max_length=200, verbose_name='Token API Shipit')),
                ('shipit_enabled', models.BooleanField(default=False, verbose_name='Activar integración Shipit')),
            ],
            options={
                'verbose_name': 'Configuración de la Tienda',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Costo de envío (CLP)'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_courier',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Courier de envío'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_estimated_days',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Días estimados de entrega'),
        ),
        migrations.AddField(
            model_name='product',
            name='height_cm',
            field=models.DecimalField(decimal_places=1, default=Decimal('10.0'), max_digits=6, verbose_name='Alto (cm)'),
        ),
        migrations.AddField(
            model_name='product',
            name='length_cm',
            field=models.DecimalField(decimal_places=1, default=Decimal('10.0'), max_digits=6, verbose_name='Largo (cm)'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_kg',
            field=models.DecimalField(decimal_places=3, default=Decimal('1.000'), max_digits=6, verbose_name='Peso (kg)'),
        ),
        migrations.AddField(
            model_name='product',
            name='width_cm',
            field=models.DecimalField(decimal_places=1, default=Decimal('10.0'), max_digits=6, verbose_name='Ancho (cm)'),
        ),
    ]
