# Generated by Django 6.1 on 2026-08-24 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0019_product_image_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Conteo de visitas'),
        ),
        migrations.AddField(
            model_name='product',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Conteo de visitas'),
        ),
    ]
