# Generated by Django 6.1 on 2026-08-24 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0020_views_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='banner1_bg_color',
            field=models.CharField(default='bg-primary text-white', max_length=30, verbose_name='Banner 1 Estilo/Color'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='banner1_subtitle',
            field=models.CharField(default='Aprovecha descuentos especiales en productos seleccionados.', max_length=300, verbose_name='Banner 1 Subtítulo'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='banner1_title',
            field=models.CharField(default='Promoción del mes', max_length=150, verbose_name='Banner 1 Título'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='banner2_bg_color',
            field=models.CharField(default='bg-success text-white', max_length=30, verbose_name='Banner 2 Estilo/Color'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='banner2_subtitle',
            field=models.CharField(default='Disfruta de envío gratis en pedidos sobre el monto mínimo.', max_length=300, verbose_name='Banner 2 Subtítulo'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='banner2_title',
            field=models.CharField(default='Envío gratis', max_length=150, verbose_name='Banner 2 Título'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='banner3_bg_color',
            field=models.CharField(default='bg-warning text-dark', max_length=30, verbose_name='Banner 3 Estilo/Color'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='banner3_subtitle',
            field=models.CharField(default='Descubre la colección más reciente para esta temporada.', max_length=300, verbose_name='Banner 3 Subtítulo'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='banner3_title',
            field=models.CharField(default='Nuevos lanzamientos', max_length=150, verbose_name='Banner 3 Título'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='footer_text',
            field=models.CharField(default='Plataforma de comercio electrónico con despacho y seguimiento en línea.', max_length=300, verbose_name='Texto de pie de página'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='site_favicon',
            field=models.ImageField(blank=True, null=True, upload_to='store_branding/', verbose_name='Favicon'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='site_logo',
            field=models.ImageField(blank=True, null=True, upload_to='store_branding/', verbose_name='Logo de la tienda'),
        ),
    ]
