# Generated by Django 6.1 on 2026-08-24 23:01

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0022_product_reviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Código del Cupón')),
                ('discount_type', models.CharField(choices=[('percentage', 'Porcentaje (%)'), ('fixed', 'Monto Fijo ($ CLP)')], default='percentage', max_length=15, verbose_name='Tipo de Descuento')),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor del Descuento')),
                ('min_purchase_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Monto Mínimo de Compra')),
                ('max_uses', models.PositiveIntegerField(blank=True, null=True, verbose_name='Límite de Usos Totales')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='Usos Realizados')),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Válido Desde')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='Válido Hasta')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cupón',
                'verbose_name_plural': 'Cupones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Monto Descontado'),
        ),
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='showcase.coupon', verbose_name='Cupón Aplicado'),
        ),
    ]
