# Generated by Django 6.1 on 2026-08-24 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0023_coupons_and_order_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='enable_live_sales_notifications',
            field=models.BooleanField(default=True, verbose_name='Habilitar avisos de compras recientes en vivo'),
        ),
    ]
