# Generated by Django 6.1 on 2026-08-25 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0024_live_sales_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='enable_whatsapp_widget',
            field=models.BooleanField(default=True, verbose_name='Habilitar botón flotante de WhatsApp'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='whatsapp_default_message',
            field=models.CharField(default='Hola! Quisiera más información sobre la tienda.', max_length=250, verbose_name='Mensaje inicial de WhatsApp por defecto'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='whatsapp_number',
            field=models.CharField(default='+56912345678', max_length=30, verbose_name='Número de WhatsApp de atención (+569...)'),
        ),
    ]
