# Generated by Django 6.1 on 2026-08-26 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0026_wishlist_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='announcement_bar_bg_color',
            field=models.CharField(default='#007bff', max_length=20, verbose_name='Color de fondo de barra de anuncios'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='announcement_bar_enabled',
            field=models.BooleanField(default=True, verbose_name='Habilitar barra de anuncios promocionales superior'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='announcement_bar_text',
            field=models.CharField(default='🚚 ¡Envío GRATIS a todo Chile por compras sobre $59.990! 🇨🇱', max_length=250, verbose_name='Texto de barra de anuncios'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='announcement_bar_text_color',
            field=models.CharField(default='#ffffff', max_length=20, verbose_name='Color de texto de barra de anuncios'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='card_style',
            field=models.CharField(default='rounded', max_length=30, verbose_name='Estilo de tarjetas de producto'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='font_family',
            field=models.CharField(default='inter', max_length=50, verbose_name='Tipografía principal de la tienda'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='hero_button_link',
            field=models.CharField(default='/products/', max_length=250, verbose_name='Enlace del botón del Hero Banner'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='hero_button_text',
            field=models.CharField(default='Explorar Catálogo 🔥', max_length=50, verbose_name='Texto del botón del Hero Banner'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='hero_subtitle',
            field=models.CharField(default='Descubre los mejores productos seleccionados especialmente para ti.', max_length=300, verbose_name='Subtítulo del Hero Banner'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='hero_title',
            field=models.CharField(default='Bienvenido a nuestra tienda', max_length=150, verbose_name='Título del Hero Banner'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='primary_color',
            field=models.CharField(default='#007bff', max_length=20, verbose_name='Color primario de la marca (HEX)'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='theme_preset',
            field=models.CharField(default='custom', max_length=50, verbose_name='Preset de tema visual'),
        ),
    ]
