# Generated by Django 6.1 on 2026-08-26 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0027_theme_and_design_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='banner1_image',
            field=models.ImageField(blank=True, null=True, upload_to='store_branding/', verbose_name='Banner 1 Imagen (Archivo)'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='banner1_image_url',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='Banner 1 Imagen (URL Directa)'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='banner2_image',
            field=models.ImageField(blank=True, null=True, upload_to='store_branding/', verbose_name='Banner 2 Imagen (Archivo)'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='banner2_image_url',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='Banner 2 Imagen (URL Directa)'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='banner3_image',
            field=models.ImageField(blank=True, null=True, upload_to='store_branding/', verbose_name='Banner 3 Imagen (Archivo)'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='banner3_image_url',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='Banner 3 Imagen (URL Directa)'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='site_favicon_url',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='Favicon (URL Directa)'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='site_logo_url',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='Logo de la tienda (URL Directa)'),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='site_favicon',
            field=models.ImageField(blank=True, null=True, upload_to='store_branding/', verbose_name='Favicon (Archivo)'),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='site_logo',
            field=models.ImageField(blank=True, null=True, upload_to='store_branding/', verbose_name='Logo de la tienda (Archivo)'),
        ),
    ]
