from django.urls import path
from .views import (
    AddBrand,
    AddCategory,
    AddDistributor,
    AddFeature,
    AddManufacturer,
    AddNewProduct,
    ArchivedProductsList,
    CartAdd,
    CartClear,
    CartDetail,
    CartRemove,
    CartUpdate,
    DeleteProduct,
    DeleteProductImage,
    EditProduct,

    GetBrands,
    GetCategories,
    GetDistributors,
    GetFeatures,
    GetManufacturers,
    GetSubcategories,
    HelloWorld,
    HomePage,
    ListProducts,
    LiveProductSearch,
    ManageAnalyticsDashboard,
    ManageAnalyticsExportCSV,
    ManageOrderDetail,
    ManageOrdersList,
    ManageOrderUpdateStatus,
    ManageSettings,
    OrderConfirmation,
    OrderCreate,
    OrderDetail,
    OrderHistory,
    PaymentFailure,
    PaymentPortal,
    PaymentProcess,
    PaymentRetry,
    ProductDetail,
    AddProductReview,
    ApplyCoupon,
    RemoveCoupon,
    ManageCoupons,
    RecentSalesNotificationAPI,
    Register,
    RestoreProduct,
    ShippingQuote,
)

urlpatterns = [
    path('', HomePage, name='home'),
    path('hello-world/', HelloWorld),
    path('products/', ListProducts, name='products'),
    path('products/live-search/', LiveProductSearch, name='liveProductSearch'),
    path('products/detail/<int:productId>/', ProductDetail, name='productDetail'),
    path('products/detail/<int:productId>/review/', AddProductReview, name='addProductReview'),


    path('products/new/', AddNewProduct, name='addProduct'),
    path('products/edit/<int:productId>/', EditProduct, name='editProduct'),
    path('products/delete/<int:productId>/', DeleteProduct, name='deleteProduct'),
    path('products/images/<int:imageId>/delete/', DeleteProductImage, name='deleteProductImage'),
    path('products/restore/<int:productId>/', RestoreProduct, name='restoreProduct'),

    path('products/archived/', ArchivedProductsList, name='archivedProducts'),
    path('products/get_categories/', GetCategories, name='getCategories'),
    path('products/get_brands/', GetBrands, name='getBrands'),
    path('products/get_manufacturers/', GetManufacturers, name='getManufacturers'),
    path('products/get_distributors/', GetDistributors, name='getDistributors'),
    path('products/get_subcategory/<int:categoryID>/', GetSubcategories, name='getCategoryById'),
    path('products/get_features/<int:categoryID>/', GetFeatures, name='getFeatures'),
    path('products/add_category/', AddCategory, name='addCategory'),
    path('products/add_brand/', AddBrand, name='addBrand'),
    path('products/add_manufacturer/', AddManufacturer, name='addManufacturer'),
    path('products/add_distributor/', AddDistributor, name='addDistributor'),
    path('products/add_feature/', AddFeature, name='addFeature'),
    path('accounts/register/', Register, name='register'),
    path('cart/', CartDetail, name='cartDetail'),
    path('cart/add/<int:productId>/', CartAdd, name='cartAdd'),
    path('cart/remove/<int:productId>/', CartRemove, name='cartRemove'),
    path('cart/update/<int:productId>/', CartUpdate, name='cartUpdate'),
    path('cart/clear/', CartClear, name='cartClear'),
    path('cart/coupon/apply/', ApplyCoupon, name='applyCoupon'),
    path('cart/coupon/remove/', RemoveCoupon, name='removeCoupon'),
    path('orders/checkout/', OrderCreate, name='orderCreate'),
    path('orders/confirmation/<int:orderId>/', OrderConfirmation, name='orderConfirmation'),
    path('orders/history/', OrderHistory, name='orderHistory'),
    path('orders/detail/<int:orderId>/', OrderDetail, name='orderDetail'),
    path('payments/portal/<int:orderId>/', PaymentPortal, name='paymentPortal'),
    path('payments/process/<int:orderId>/', PaymentProcess, name='paymentProcess'),
    path('payments/failure/<int:orderId>/', PaymentFailure, name='paymentFailure'),
    path('payments/retry/<int:orderId>/', PaymentRetry, name='paymentRetry'),
    path('manage/orders/', ManageOrdersList, name='manageOrders'),
    path('manage/orders/<int:orderId>/', ManageOrderDetail, name='manageOrderDetail'),
    path('manage/orders/<int:orderId>/update/', ManageOrderUpdateStatus, name='manageOrderUpdateStatus'),
    path('manage/dashboard/', ManageAnalyticsDashboard, name='manageAnalyticsDashboard'),
    path('manage/dashboard/export-csv/', ManageAnalyticsExportCSV, name='manageAnalyticsExportCSV'),
    path('manage/settings/', ManageSettings, name='manageSettings'),
    path('manage/coupons/', ManageCoupons, name='manageCoupons'),
    path('api/recent-sales/', RecentSalesNotificationAPI, name='recentSalesAPI'),
    path('shipping/quote/', ShippingQuote, name='shippingQuote'),
]