from django.urls import path
from .views import (
    AddBrand,
    AddCategory,
    AddDistributor,
    AddFeature,
    AddManufacturer,
    AddNewProduct,
    ArchivedProductsList,
    CartAdd,
    CartClear,
    CartDetail,
    CartRemove,
    CartUpdate,
    DeleteProduct,
    EditProduct,
    GetBrands,
    GetCategories,
    GetDistributors,
    GetFeatures,
    GetManufacturers,
    GetSubcategories,
    HelloWorld,
    HomePage,
    ListProducts,
    ManageOrderDetail,
    ManageOrdersList,
    ManageOrderUpdateStatus,
    OrderConfirmation,
    OrderCreate,
    OrderDetail,
    OrderHistory,
    ProductDetail,
    Register,
    RestoreProduct,
)

urlpatterns = [
    path('', HomePage, name='home'),
    path('hello-world/', HelloWorld),
    path('products/', ListProducts, name='products'),
    path('products/detail/<int:productId>/', ProductDetail, name='productDetail'),
    path('products/new/', AddNewProduct, name='addProduct'),
    path('products/edit/<int:productId>/', EditProduct, name='editProduct'),
    path('products/delete/<int:productId>/', DeleteProduct, name='deleteProduct'),
    path('products/restore/<int:productId>/', RestoreProduct, name='restoreProduct'),
    path('products/archived/', ArchivedProductsList, name='archivedProducts'),
    path('products/get_categories/', GetCategories, name='getCategories'),
    path('products/get_brands/', GetBrands, name='getBrands'),
    path('products/get_manufacturers/', GetManufacturers, name='getManufacturers'),
    path('products/get_distributors/', GetDistributors, name='getDistributors'),
    path('products/get_subcategory/<int:categoryID>/', GetSubcategories, name='getCategoryById'),
    path('products/get_features/<int:categoryID>/', GetFeatures, name='getFeatures'),
    path('products/add_category/', AddCategory, name='addCategory'),
    path('products/add_brand/', AddBrand, name='addBrand'),
    path('products/add_manufacturer/', AddManufacturer, name='addManufacturer'),
    path('products/add_distributor/', AddDistributor, name='addDistributor'),
    path('products/add_feature/', AddFeature, name='addFeature'),
    path('accounts/register/', Register, name='register'),
    path('cart/', CartDetail, name='cartDetail'),
    path('cart/add/<int:productId>/', CartAdd, name='cartAdd'),
    path('cart/remove/<int:productId>/', CartRemove, name='cartRemove'),
    path('cart/update/<int:productId>/', CartUpdate, name='cartUpdate'),
    path('cart/clear/', CartClear, name='cartClear'),
    path('orders/checkout/', OrderCreate, name='orderCreate'),
    path('orders/confirmation/<int:orderId>/', OrderConfirmation, name='orderConfirmation'),
    path('orders/history/', OrderHistory, name='orderHistory'),
    path('orders/detail/<int:orderId>/', OrderDetail, name='orderDetail'),
    path('manage/orders/', ManageOrdersList, name='manageOrders'),
    path('manage/orders/<int:orderId>/', ManageOrderDetail, name='manageOrderDetail'),
    path('manage/orders/<int:orderId>/update/', ManageOrderUpdateStatus, name='manageOrderUpdateStatus'),
]